version: '3.7'

services:
  db:
    image: "postgres:14-alpine"
    container_name: postgresql
    volumes:
      - ./db/postqres/:/var/lib/postgresql/data
    env_file:
      - ./.env
  web:
    build: .
    container_name: drf_application
    command: bash entrypoint.sh
    volumes:
      - .:/usr/src/app
    ports:
      - 8000:8000
    env_file:
      - ./.env
  redis:
    image: redis
    container_name: redis
    volumes:
      - ./db/redis/:/var/lib/redis
    ports:
      - 6379:6379

