version: '3.7'

services:
  web:
    image: drf_application 
    container_name: drf_application
    command: bash entrypoint.sh
    volumes:
      - .:/usr/src/app
    ports:
      - 8000:8000
    env_file:
      - ./.env
