version: '3.7'

services:
  web:
    image: backend_web 
    container_name: drf_project
    command: bash entrypoint.sh
    volumes:
      - .:/usr/src/app
    ports:
      - 8000:8000
    env_file:
      - ./keys.sh
