# Generated by Django 4.0 on 2022-01-31 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='total_bets_sum',
            field=models.PositiveIntegerField(default=0, verbose_name='total sum of all bets for this challenge'),
        ),
    ]
