# Generated by Django 4.0 on 2022-02-04 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='challenge',
            old_name='date_finish',
            new_name='datetime_finish',
        ),
    ]
