# Generated by Django 4.0 on 2022-01-31 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0002_alter_challenge_total_bets_sum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='video_example',
            field=models.FileField(blank=True, null=True, upload_to='video_examples', verbose_name='example of perform'),
        ),
    ]
