# Generated by Django 4.0 on 2022-02-04 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0002_rename_date_finish_challenge_datetime_finish'),
    ]

    operations = [
        migrations.RenameField(
            model_name='challenge',
            old_name='date_start',
            new_name='datetime_start',
        ),
    ]
