# Generated by Django 4.0 on 2022-01-31 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_is_activated_alter_user_registration_date_and_more'),
        ('challenges', '0003_alter_challenge_video_example'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChallengeMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='challenges.challenge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
        migrations.CreateModel(
            name='ChallengeAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_answer', models.FileField(upload_to='video_answer', verbose_name='video answer on chellange')),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='challenges.challenge')),
                ('challenge_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='challenges.challengemember')),
            ],
        ),
        migrations.CreateModel(
            name='ChallegeWinner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='challenges.challenge')),
                ('challenge_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='challenges.challengemember')),
            ],
        ),
    ]
