# Generated by Django 4.0 on 2022-01-31 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_is_activated_alter_user_registration_date_and_more'),
        ('challenges', '0004_challengemember_challengeanswer_challegewinner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challegewinner',
            name='challenge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='challenges.challenge', verbose_name='challenge'),
        ),
        migrations.AlterField(
            model_name='challegewinner',
            name='challenge_member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='challenges.challengemember', verbose_name='challenge member'),
        ),
        migrations.AlterField(
            model_name='challengeanswer',
            name='challenge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='challenges.challenge', verbose_name='challenge'),
        ),
        migrations.AlterField(
            model_name='challengeanswer',
            name='challenge_member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='challenges.challengemember', verbose_name='challenge member'),
        ),
        migrations.AlterField(
            model_name='challengemember',
            name='challenge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='challenges.challenge', verbose_name='challenge'),
        ),
        migrations.AlterField(
            model_name='challengemember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user', verbose_name='user'),
        ),
    ]
