# Generated by Django 4.0 on 2022-02-07 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0005_alter_challenge_video_example_challengebalace'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='is_free',
            field=models.BooleanField(default=False, verbose_name='is challenge freee'),
        ),
    ]
