# Generated by Django 4.0 on 2022-01-31 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0005_alter_challegewinner_challenge_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='challenge name'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='slug',
            field=models.SlugField(max_length=200, unique=True, verbose_name='slug'),
        ),
    ]
