# Generated by Django 4.0 on 2022-02-07 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0006_challenge_is_free'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChallengeBalace',
            new_name='ChallengeBalance',
        ),
    ]
