# Generated by Django 4.0 on 2022-02-01 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0006_alter_challenge_name_alter_challenge_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='is challenge active'),
        ),
    ]
