# Generated by Django 4.0 on 2022-02-08 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0007_rename_challengebalace_challengebalance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challengebalance',
            name='challenge',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='balance', to='challenges.challenge'),
        ),
    ]
