# Generated by Django 4.0 on 2022-02-01 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0007_alter_challenge_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='bet',
            field=models.PositiveIntegerField(default=0, verbose_name='amount coins for accept challenge'),
        ),
    ]
