# Generated by Django 4.0 on 2022-02-10 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0008_alter_challengebalance_challenge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='total_bets_sum',
        ),
    ]
