# Generated by Django 4.0 on 2022-02-10 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0009_remove_challenge_total_bets_sum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='is_free',
        ),
    ]
