# Generated by Django 4.0 on 2022-02-12 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0010_remove_challenge_is_free'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChallegeWinner',
            new_name='ChallengeWinner',
        ),
        migrations.AlterField(
            model_name='challenge',
            name='description',
            field=models.CharField(max_length=500, verbose_name='challenge description'),
        ),
        migrations.AlterField(
            model_name='challengeanswer',
            name='video_answer',
            field=models.FileField(upload_to='video_answers', verbose_name='video answer on challenge'),
        ),
    ]
