# Generated by Django 4.0 on 2022-02-15 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0012_alter_challenge_video_example'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challengeanswer',
            name='video_answer',
            field=models.FileField(upload_to='challenge_answers/', verbose_name='video answer on challenge'),
        ),
    ]
