# Generated by Django 4.0 on 2021-12-31 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='training_experience',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='How long does user train in total'),
        ),
    ]
