# Generated by Django 4.0 on 2022-01-17 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_is_email_confirmed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_email_confirmed',
        ),
    ]
