# Generated by Django 4.0 on 2022-01-21 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_notconfirmedemail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_activated',
            field=models.BooleanField(default=False, verbose_name='Has user activated account?'),
        ),
        migrations.AlterField(
            model_name='user',
            name='registration_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date when user was registered'),
        ),
        migrations.AlterField(
            model_name='user',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='field intends for using in url (slug)'),
        ),
    ]
