# Generated by Django 4.0 on 2022-02-07 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_userbalance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbalance',
            name='coins_amount',
            field=models.PositiveIntegerField(default=0, verbose_name='coins amount'),
        ),
    ]
