# Generated by Django 4.0 on 2022-02-07 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_userbalance_coins_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbalance',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='balance', to='users.user'),
        ),
    ]
